[project]
name = "mcp-python-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "mcp[all,cli]>=1.22.0",
    "requests>=2.32.5",
]
